### ISSUE TITLE
Running multiple tasks fails

### ISSUE THREAD

**Issue by aop** [bezoerb/gulp-php2html#4]
gulp.task('php',function() {
    return gulp.src([ "./*.php",
                      ])
    .pipe(php2html())
    .pipe(gulp.dest("./build/"));
})
gulp.task('php-en',function() {
    return gulp.src([
                      "./en/*.php",
                      ])
    .pipe(php2html())
    .pipe(gulp.dest("./build/en/"));
})
gulp.task('default', ['php', 'php-en', ], function() {});

causes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at startServer (/home/apetas/koodaus/myproject/node_modules/gulp-php2html/index.js:106:12)
    at Stream.php2html (/home/apetas/koodaus/myproject/node_modules/gulp-php2html/index.js:130:23)
    at _end (/home/apetas/koodaus/myproject/node_modules/gulp-php2html/node_modules/event-stream/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/apetas/koodaus/myproject/node_modules/gulp-php2html/node_modules/event-stream/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/home/apetas/koodaus/myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)

**Comment by bezoerb** [comment]
@aop this is because both tasks try to use the default port. So the second one throws `EADDRINUSE` because it could not connect. Try to set different ports for each task.
```javascript
...
.pipe(php2html({port: 8081}))
...
```

**Comment by aop** [comment]
That's what I figured out too. Works.
How does php2html work in the background? Why does it need to reserve a port that is the same in-between the jobs?

**Comment by bezoerb** [comment]
@aop The data gets fetched via `http` with some `php` middleware.
Just released a new version where manually setting the port for parallel calls isn't required anymore.
